namespace: dev

apps:
  - name: ui
    port: 8080
    targets: "mgmt-service.dev:8080#5"
    tier: frontend

  - name: mgmt
    port: 8080
    targets: "ui-service.dev:8080#5,mock-mongo-service.dev:8080#2"
    tier: backend
    
  - name: mock-mongo
    port: 8080
    targets: ""
    tier: database

  # - name: collector
  #   port: 8080
  #   targets: "mgmt-service.dev:8080#1"
  #   tier: data-path

