namespace: qa

apps:
  - name: ui
    port: 8080
    targets: "mgmt-service.qa:8080#5"
    tier: frontend

  - name: mgmt
    port: 8080
    targets: "ui-service.qa:8080#2,mock-mongo-service.qa:8080#3"
    tier: backend
    
  - name: mock-mongo
    port: 8080
    targets: ""
    tier: database

  - name: collector
    port: 8080
    targets: "mgmt-service.qa:8080#1,mgmt-service.dev:8080#5"
    tier: data-path

